In [1]:
import numpy as np

In [15]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [16]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
b = np.array(((1,2,3,4),(5,6,7,8),(9,10,11,12)))

In [23]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
a = np.array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [91]:
merah = a[0,1:4]
print("merah :",merah)
hijau = a[0::2, ::2]
print("hijau :",hijau)
biru = a[1:4, 0]
print("biru :",biru)
pink = a[0:5, 1]
print("pink :",pink)

merah : [12 13 14]
hijau : [[11 13 15]
 [21 23 25]
 [31 33 35]]
biru : [16 21 26]
pink : [12 17 22 27 32]
